# Copyright 2014-2022 Will Cunningham
#
# This file is part of FastMath.
#
# Licensed under the GNU General Public License 3.0 (the "License").
# A copy of the License may be obtained with this software package or at
#
#     https://www.gnu.org/licenses/gpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any
# modifications or derivative works of this file must retain this copyright
# notice, and modified files must contain a notice indicating that they have
# been altered from the originals.
#
# FastMath is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.

name: buildrpm

on:
  workflow_run:
    workflows: ["release"]
    branches: [master]
    types: [completed]

jobs:
  buildrpm:
    runs-on: ubuntu-latest
    container: centos:centos7
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out head
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install rpmbuild
        run: yum install -y rpm-build
      - name: Read version
        run: |
          VERSION=`cat VERSION`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build tarball
        run: |
          mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mkdir fastmath-$VERSION
          cp -r include configure LICENSE Makefile.in missing fastmath-$VERSION
          tar cvzf fastmath-$VERSION.tar.gz fastmath-$VERSION
          mv fastmath-$VERSION.tar.gz $HOME/rpmbuild/SOURCES
      - name: Generate spec
        run: |
          bash ./build-rpm-spec.sh
          mv fastmath.spec $HOME/rpmbuild/SPECS
      - name: Build RPM
        run: rpmbuild -bs $HOME/rpmbuild/SPECS/fastmath.spec
      - name: Test RPM installation
        run: rpm -ivvh $HOME/rpmbuild/SRPMS/fastmath-$VERSION-1.src.rpm
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/wjcunningham7/fastmath/releases/${{ env.VERSION }}/assets
          asset_name: fastmath-${{ env.VERSION }}-1.src.rpm
          asset_path: /github/home/rpmbuild/SRPMS/fastmath-${{ env.VERSION }}-1.src.rpm
          asset_content_type: application/x-rpm
