name: buildrpm

on:
  push:
    branches:
      - master
      - add-rpm-build-recipe

jobs:
  buildrpm:
    runs-on: ubuntu-latest
    container: centos:centos7
    steps:
      - name: Check out head
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install rpmbuild
        run: yum install -y rpm-build
      - name: Read version
        run: |
          VERSION=`cat VERSION`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build tarball
        run: |
          mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mkdir fastmath-$VERSION
          cp -r include configure LICENSE Makefile.in missing fastmath-$VERSION
          tar cvzf fastmath-$VERSION.tar.gz fastmath-$VERSION
          mv fastmath-$VERSION.tar.gz $HOME/rpmbuild/SOURCES
      - name: Generate spec
        run: |
          bash ./build-rpm-spec.sh
          mv fastmath.spec $HOME/rpmbuild/SPECS
      - name: Build RPM
        run: rpmbuild -bs $HOME/rpmbuild/SPECS/fastmath.spec
      - name: Test RPM installation
        run: rpm -ivvh $HOME/rpmbuild/SRPMS/fastmath-$VERSION-1.src.rpm
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: FastMath RPM
          path: /github/home/rpmbuild/SRPMS/fastmath-${{ env.VERSION }}-1.src.rpm
