on:
  pull_request

name: Changelog Reminder

jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.3.0
      with:
        changelog_regex: 'CHANGELOG.md'
        customPrMessage: |
          Hello. You may have forgotten to update the changelog!
          Please edit [`CHANGELOG.md`](/AgnostiqHQ/covalent/blob/master/CHANGELOG.md) with a one-to-two sentence description of the change in the UNRELEASED section. You may include a small working example for new features.
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
