name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Read version
        run: |
          VERSION="$(cat ./VERSION)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE=v$VERSION" >> $GITHUB_ENV
      - name: Tag commit
        id: push
        run: |
          git config user.name "FastMathOpsBot"
          git config user.email "fastmathopsbot@users.noreply.github.com"
          git tag -a $RELEASE -m "Release $RELEASE"
          git remote set-url origin https://${{ secrets.FASTMATH_OPS_BOT_TOKEN }}@github.com/wjcunningham7/fastmath.git
          git push origin $RELEASE
      - name: Generate release message
        id: message
        run: |
          begin=$(grep -n "\b${VERSION}\b" ./CHANGELOG.md | cut -d ':' -f 1)
          previous_version=$(git describe --abbrev=0 $RELEASE^ | cut -c2-)
          end=$(tail -n +$((begin+1)) ./CHANGELOG.md | grep -n -m 1 "\b${previous_version}\b" | cut -d ':' -f 1)
          echo 'MESSAGE<<EOF' >> $GITHUB_ENV
          tail +$begin ./CHANGELOG.md | head -$end >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create release
        if: ${{ steps.push.outcome == 'success' && steps.message.outcome == 'success' }}
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.MESSAGE }}
          token: ${{ secrets.FASTMATH_OPS_BOT_TOKEN }}
          tag: ${{ env.RELEASE }}
          prerelease: true
